import { WafDetectionResult } from '../../types/sqlScanner';

export class WafDetector {
  private static WAF_SIGNATURES: { name: string; headerPattern?: RegExp; bodyPattern?: RegExp; statusCodes?: number[] }[] = [
    {
      name: 'Cloudflare',
      headerPattern: /cf-ray|cf-cache-status|cloudflare|__cfduid/i,
      bodyPattern: /attention required.*cloudflare|cloudflare ray id|error 1020.*access denied/i,
      statusCodes: [403, 503],
    },
    {
      name: 'AWS WAF',
      headerPattern: /x-amzn-requestid|x-amz-cf-id|awselb|x-amz-id-2/i,
      bodyPattern: /403 Forbidden.*AWS WAF|Request blocked by administrative rules|awswaf/i,
      statusCodes: [403],
    },
    {
      name: 'Akamai Kona',
      headerPattern: /akamai-x-get-request-id|x-akamai-transformed|ak_bmsc/i,
      bodyPattern: /AkamaiGHost|Reference&#32;&#35;|Access Denied - Akamai/i,
      statusCodes: [403],
    },
    {
      name: 'Imperva Incapsula',
      headerPattern: /x-iinfo|incap_ses|visid_incap|_incap_/i,
      bodyPattern: /incapsula incident id|_Incapsula_Resource|Request unsuccessful\. Incapsula incident/i,
      statusCodes: [403],
    },
    {
      name: 'ModSecurity',
      headerPattern: /mod_security|NOYB/i,
      bodyPattern: /ModSecurity Action|This error was generated by ModSecurity|blocked by ModSecurity/i,
      statusCodes: [403, 406],
    },
    {
      name: 'F5 BIG-IP ASM',
      headerPattern: /x-cnection|bigipserver|ts[0-9a-f]{6,}/i,
      bodyPattern: /The requested URL was rejected\. Please consult with your administrator|support ID: \d+/i,
      statusCodes: [403, 501],
    },
    {
      name: 'Fastly / Signal Sciences',
      headerPattern: /x-sigsci-|fastly-restarts|x-fastly-request-id/i,
      bodyPattern: /Fastly error: unknown domain|Signal Sciences Web Protection/i,
      statusCodes: [403, 406],
    },
    {
      name: 'Barracuda WAF',
      headerPattern: /barra_counter_session|barracuda_/i,
      bodyPattern: /You have been blocked by Barracuda Web Application Firewall/i,
      statusCodes: [403],
    },
    {
      name: 'Citrix NetScaler',
      headerPattern: /ns_af=|citrix_ns_id|ns_session/i,
      bodyPattern: /NetScaler AppFirewall|Access Denied - Citrix/i,
      statusCodes: [403],
    },
    {
      name: 'Fortinet FortiWeb',
      headerPattern: /fortiwafsid=|x-fortiwaf/i,
      bodyPattern: /Server Unavailable.*FortiWeb|Protected by FortiWeb/i,
      statusCodes: [403],
    },
    {
      name: 'Alibaba Cloud WAF',
      headerPattern: /aliyun_waf_|x-ali-waf/i,
      bodyPattern: /Sorry, your request has been blocked by Alibaba Cloud WAF/i,
      statusCodes: [405, 403],
    },
    {
      name: 'Microsoft Azure WAF',
      headerPattern: /x-ms-request-id|x-azure-ref|x-fd-features/i,
      bodyPattern: /Our services aren't available right now.*Azure|Request Blocked.*Azure WAF/i,
      statusCodes: [403],
    },
    {
      name: 'Google Cloud Armor',
      headerPattern: /x-cloud-trace-context|x-goog-authenticated-user/i,
      bodyPattern: /Your client does not have permission to get URL.*Google|403 Forbidden.*Google/i,
      statusCodes: [403],
    },
    {
      name: 'Palo Alto Networks',
      headerPattern: /x-pan-signature|pan-os/i,
      bodyPattern: /Access Denied.*Palo Alto Networks|has been blocked in accordance with company policy/i,
      statusCodes: [403],
    },
    {
      name: 'Sucuri CloudProxy',
      headerPattern: /x-sucuri-id|x-sucuri-cache/i,
      bodyPattern: /Access Denied - Sucuri Website Firewall|sucuri cloudproxy/i,
      statusCodes: [403],
    },
    {
      name: 'Wallarm WAF',
      headerPattern: /x-wallarm/i,
      bodyPattern: /Blocked by Wallarm/i,
      statusCodes: [403],
    },
    {
      name: 'Radware AppWall',
      headerPattern: /x-rdwr-|rdwr_session/i,
      bodyPattern: /Unauthorized Activity Has Been Detected.*Radware/i,
      statusCodes: [403],
    },
    {
      name: 'Wordfence',
      headerPattern: /wfvt_|wordfence_lh/i,
      bodyPattern: /Generated by Wordfence|Your access to this site has been limited/i,
      statusCodes: [403],
    },
    {
      name: 'Reblaze WAF',
      headerPattern: /rbzid=|x-reblaze/i,
      bodyPattern: /Current session has been terminated.*reblaze/i,
      statusCodes: [403],
    },
    {
      name: 'Tencent Cloud WAF',
      headerPattern: /waf.tencent-cloud|x-tc-waf/i,
      bodyPattern: /tencent-cloud-waf|blocked by Tencent Cloud WAF/i,
      statusCodes: [403],
    },
    {
      name: 'SonicWall WAF',
      headerPattern: /x-sonicwall|sonicwall/i,
      bodyPattern: /This request is blocked by the SonicWALL|SonicWALL Web Application Firewall/i,
      statusCodes: [403],
    },
    {
      name: 'WebKnight',
      headerPattern: /webknight/i,
      bodyPattern: /WebKnight Application Firewall Alert|aqtr_status/i,
      statusCodes: [404, 403],
    },
    {
      name: 'NAXSI',
      headerPattern: /x-naxsi-sig/i,
      bodyPattern: /blocked by naxsi|request blocked by NAXSI/i,
      statusCodes: [400, 403],
    },
    {
      name: 'DataDome',
      headerPattern: /datadome=|x-datadome-response/i,
      bodyPattern: /datadome\.js|Please solve the challenge below.*DataDome/i,
      statusCodes: [403],
    },
    {
      name: 'PerimeterX / HUMAN',
      headerPattern: /_px3=|_pxhd=|x-px-/i,
      bodyPattern: /perimeterx\.com|Access to this page has been denied.*HUMAN/i,
      statusCodes: [403],
    },
    {
      name: 'Kasada',
      headerPattern: /x-kpsdk-ct|x-kpsdk-cd/i,
      bodyPattern: /ips\.js|kpsdk/i,
      statusCodes: [403],
    },
  ];

  /**
   * Evaluates response headers and body for presence of Web Application Firewall / CDN block layers
   */
  public static inspect(headers: { name: string; value: string }[], body: string, statusCode: number): WafDetectionResult {
    const headerString = headers.map((h) => `${h.name}: ${h.value}`).join('\n');
    const evidence: string[] = [];

    for (const waf of WafDetector.WAF_SIGNATURES) {
      let matched = false;

      if (waf.headerPattern && waf.headerPattern.test(headerString)) {
        evidence.push(`${waf.name} header signature matched`);
        matched = true;
      }

      if (waf.bodyPattern && waf.bodyPattern.test(body)) {
        evidence.push(`${waf.name} block page pattern detected in body`);
        matched = true;
      }

      if (matched) {
        return {
          detected: true,
          wafName: waf.name,
          confidence: 'High',
          evidence,
        };
      }
    }

    if (statusCode === 403 || statusCode === 406) {
      if (/waf|blocked|firewall|forbidden|security incident/i.test(body)) {
        return {
          detected: true,
          wafName: 'Generic WAF / Security Filter',
          confidence: 'Medium',
          evidence: [`Received HTTP ${statusCode} with security filtering keywords in body`],
        };
      }
    }

    return {
      detected: false,
      confidence: 'Informational',
      evidence: [],
    };
  }

  /**
   * Maps a detected WAF name to optimal metamorphic bypass transformations
   */
  public static getRecommendedTransforms(wafName?: string): string[] {
    if (!wafName) return ['E1_INLINE_COMMENT_SPACE', 'E6_URL_HEX_ENCODING'];

    const lower = wafName.toLowerCase();
    if (lower.includes('cloudflare')) {
      return ['E1_INLINE_COMMENT_SPACE', 'E3_VERSIONED_COMMENTS', 'E11_STRING_CONCATENATION_BYPASS', 'E9_RANDOM_CASE_MUTATION'];
    }
    if (lower.includes('aws')) {
      return ['E4_NON_STANDARD_WHITESPACE', 'E7_DOUBLE_URL_ENCODING', 'E10_LOGICAL_OPERATOR_SUBSTITUTION'];
    }
    if (lower.includes('modsecurity')) {
      return ['E2_C_STYLE_COMMENTS', 'E5_TAB_NEWLINE_MUTATION', 'E12_HEX_LITERAL_ENCODING'];
    }
    if (lower.includes('imperva') || lower.includes('incapsula')) {
      return ['E8_UNICODE_NORMALIZATION', 'E13_CHAR_FUNCTION_ENCODING', 'E1_INLINE_COMMENT_SPACE'];
    }
    if (lower.includes('akamai')) {
      return ['E11_STRING_CONCATENATION_BYPASS', 'E6_URL_HEX_ENCODING', 'E10_LOGICAL_OPERATOR_SUBSTITUTION'];
    }
    if (lower.includes('fortinet') || lower.includes('barracuda')) {
      return ['E1_INLINE_COMMENT_SPACE', 'E12_HEX_LITERAL_ENCODING', 'E4_NON_STANDARD_WHITESPACE'];
    }

    return ['E1_INLINE_COMMENT_SPACE', 'E6_URL_HEX_ENCODING', 'E10_LOGICAL_OPERATOR_SUBSTITUTION'];
  }

  public static getSupportedWafs(): string[] {
    return WafDetector.WAF_SIGNATURES.map((w) => w.name);
  }

  public static detect(
    headers: { name: string; value: string }[] | Record<string, string>,
    body: string,
    statusCode: number = 200,
    cookieNames: string[] = []
  ): WafDetectionResult {
    let normalizedHeaders: { name: string; value: string }[] = [];
    if (Array.isArray(headers)) {
      normalizedHeaders = [...headers];
    } else if (headers && typeof headers === 'object') {
      normalizedHeaders = Object.entries(headers).map(([name, value]) => ({ name, value: String(value) }));
    }
    if (cookieNames && cookieNames.length > 0) {
      normalizedHeaders.push({ name: 'Cookie', value: cookieNames.join('; ') });
    }
    return WafDetector.inspect(normalizedHeaders, body, statusCode);
  }
}
