import { WafDetectionResult } from '../../types/sqlScanner';

export class WafDetector {
  private static WAF_SIGNATURES: { name: string; headerPattern?: RegExp; bodyPattern?: RegExp; statusCodes?: number[] }[] = [
    {
      name: 'Cloudflare',
      headerPattern: /cf-ray|cf-cache-status|cloudflare/i,
      bodyPattern: /attention required.*cloudflare|cloudflare ray id/i,
      statusCodes: [403, 503],
    },
    {
      name: 'AWS WAF',
      headerPattern: /x-amzn-requestid|x-amz-cf-id|awselb/i,
      bodyPattern: /403 Forbidden.*AWS WAF|Request blocked by administrative rules/i,
      statusCodes: [403],
    },
    {
      name: 'Akamai Kona',
      headerPattern: /akamai-x-get-request-id|x-akamai-transformed/i,
      bodyPattern: /AkamaiGHost|Reference&#32;&#35;/i,
      statusCodes: [403],
    },
    {
      name: 'Imperva Incapsula',
      headerPattern: /x-iinfo|incap_ses|visid_incap/i,
      bodyPattern: /incapsula incident id|_Incapsula_Resource/i,
      statusCodes: [403],
    },
    {
      name: 'ModSecurity',
      headerPattern: /mod_security|NOYB/i,
      bodyPattern: /ModSecurity Action|This error was generated by ModSecurity/i,
      statusCodes: [403, 406],
    },
    {
      name: 'F5 BIG-IP ASM',
      headerPattern: /x-cnection|bigipserver/i,
      bodyPattern: /The requested URL was rejected\. Please consult with your administrator/i,
      statusCodes: [403, 501],
    },
  ];

  /**
   * Evaluates response headers and body for presence of Web Application Firewall / CDN block layers
   */
  public static inspect(headers: { name: string; value: string }[], body: string, statusCode: number): WafDetectionResult {
    const headerString = headers.map((h) => `${h.name}: ${h.value}`).join('\n');
    const evidence: string[] = [];

    for (const waf of WafDetector.WAF_SIGNATURES) {
      let matched = false;

      if (waf.headerPattern && waf.headerPattern.test(headerString)) {
        evidence.push(`${waf.name} header signature matched`);
        matched = true;
      }

      if (waf.bodyPattern && waf.bodyPattern.test(body)) {
        evidence.push(`${waf.name} block page pattern detected in body`);
        matched = true;
      }

      if (matched) {
        return {
          detected: true,
          wafName: waf.name,
          confidence: 'High',
          evidence,
        };
      }
    }

    if (statusCode === 403 || statusCode === 406) {
      if (/waf|blocked|firewall|forbidden|security incident/i.test(body)) {
        return {
          detected: true,
          wafName: 'Generic WAF / Security Filter',
          confidence: 'Medium',
          evidence: [`Received HTTP ${statusCode} with security filtering keywords in body`],
        };
      }
    }

    return {
      detected: false,
      confidence: 'Informational',
      evidence: [],
    };
  }
}
