//! Structured evidence generated by timing analysis.

use serde::{Deserialize, Serialize};
use ucma_statistics::{MannWhitneyResult, SampleSummary, SprtDecision};

/// Verifiable evidence for a time-based blind SQL injection observation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimingEvidence {
    pub baseline_summary: SampleSummary,
    pub probe_summary: SampleSummary,
    pub control_samples: Vec<f64>,
    pub probe_samples: Vec<f64>,
    pub sprt_decision: SprtDecision,
    pub sprt_llr: f64,
    pub mann_whitney: Option<MannWhitneyResult>,
    pub expected_delay_seconds: f64,
    pub observed_effect_seconds: f64,
    pub is_confirmed: bool,
}
