/**
 * UCMA-X — Master 11-Dimensional SQL Injection Taxonomy Catalog
 * Formal taxonomy representation defining mechanisms, contexts, oracles, lifecycles, and compatibility rules.
 */

import { DbmsType, InjectionContext, ParameterLocation } from '../../../types/sqlScanner';

export type TechniqueLifecycle = 'CONFIRMED' | 'CANDIDATE' | 'RESEARCH' | 'DEPRECATED' | 'UNSUPPORTED';

export type PriorityLevel = 'P0' | 'P1' | 'P2' | 'P3';

export interface TaxonomyDimensionNode {
  id: string;
  name: string;
  dimension: string;
  priority: PriorityLevel;
  status: TechniqueLifecycle;
  description: string;
  applicableDbms: DbmsType[] | 'ALL';
  applicableContexts: InjectionContext[] | 'ALL';
  applicableTransports: ParameterLocation[] | 'ALL';
  researchSource: string;
}

export const MECHANISMS: Record<string, TaxonomyDimensionNode> = {
  M01: {
    id: 'M01',
    name: 'Boolean-Based Differential Inference',
    dimension: 'Mechanism',
    priority: 'P0',
    status: 'CONFIRMED',
    description: 'Infer database state bit-by-bit by evaluating truth-value expressions causing observable page/status divergence.',
    applicableDbms: 'ALL',
    applicableContexts: 'ALL',
    applicableTransports: 'ALL',
    researchSource: 'OWASP WSTG-INPV-05; Halfond & Orso (2006)',
  },
  M02: {
    id: 'M02',
    name: 'Error-Based Type Coercion / XML / Subquery Extraction',
    dimension: 'Mechanism',
    priority: 'P0',
    status: 'CONFIRMED',
    description: 'Trigger database runtime errors (e.g. CAST to int, ExtractValue, group by duplicate key) that leak extracted data.',
    applicableDbms: ['PostgreSQL', 'Microsoft SQL Server', 'MySQL', 'Oracle'],
    applicableContexts: ['numeric', 'single_quote_string', 'double_quote_string', 'parenthesized_string', 'where_clause', 'having_clause'],
    applicableTransports: 'ALL',
    researchSource: 'CWE-209; PortSwigger SQLi Lab 03',
  },
  M03: {
    id: 'M03',
    name: 'UNION-Based Canary & Set Extension',
    dimension: 'Mechanism',
    priority: 'P0',
    status: 'CONFIRMED',
    description: 'Extend original query results using UNION SELECT with type-compatible canary markers to read metadata directly in-band.',
    applicableDbms: 'ALL',
    applicableContexts: ['numeric', 'single_quote_string', 'double_quote_string', 'parenthesized_string', 'where_clause'],
    applicableTransports: 'ALL',
    researchSource: 'CWE-89; OWASP WSTG-INPV-05',
  },
  M04: {
    id: 'M04',
    name: 'Time-Based Sequential Latency Probing (SPRT)',
    dimension: 'Mechanism',
    priority: 'P0',
    status: 'CONFIRMED',
    description: 'Inject database sleep / delay primitives and evaluate response latency with sequential hypothesis testing.',
    applicableDbms: 'ALL',
    applicableContexts: 'ALL',
    applicableTransports: 'ALL',
    researchSource: 'Wald (1945) SPRT; PortSwigger Blind SQLi',
  },
  M05: {
    id: 'M05',
    name: 'Stacked Query Multi-Statement Execution',
    dimension: 'Mechanism',
    priority: 'P1',
    status: 'CONFIRMED',
    description: 'Execute independent semicolon-separated SQL statements supported by database driver capabilities.',
    applicableDbms: ['Microsoft SQL Server', 'PostgreSQL', 'MySQL', 'SQLite'],
    applicableContexts: ['numeric', 'single_quote_string', 'where_clause'],
    applicableTransports: 'ALL',
    researchSource: 'sqlmap stacked query engine',
  },
  M06: {
    id: 'M06',
    name: 'Dynamic ORDER BY / Sorting Invariant Validation',
    dimension: 'Mechanism',
    priority: 'P0',
    status: 'CONFIRMED',
    description: 'Evaluate column index and CASE expression sorting boundaries in unquoted/identifier parameters.',
    applicableDbms: 'ALL',
    applicableContexts: ['order_by_clause', 'group_by_clause', 'identifier'],
    applicableTransports: ['query', 'body_form', 'body_json'],
    researchSource: 'PortSwigger SQLi in ORDER BY; OWASP Query Builders',
  },
  M07: {
    id: 'M07',
    name: 'Second-Order Workflow & Asynchronous Storage Injection',
    dimension: 'Mechanism',
    priority: 'P1',
    status: 'CANDIDATE',
    description: 'Store unescaped payload at source endpoint; verify execution at secondary consumer endpoint or background worker.',
    applicableDbms: 'ALL',
    applicableContexts: 'ALL',
    applicableTransports: 'ALL',
    researchSource: 'PortSwigger Second-Order SQLi (00100210)',
  },
  M08: {
    id: 'M08',
    name: 'Out-of-Band (OAST) Network Interaction',
    dimension: 'Mechanism',
    priority: 'P1',
    status: 'CANDIDATE',
    description: 'Trigger outbound DNS / HTTP / SMB network interactions to an authorized collaborator gateway.',
    applicableDbms: ['Oracle', 'Microsoft SQL Server', 'MySQL', 'PostgreSQL'],
    applicableContexts: 'ALL',
    applicableTransports: 'ALL',
    researchSource: 'Burp Collaborator / OAST Standard',
  },
  M09: {
    id: 'M09',
    name: 'Relational Metamorphic Testing (TLP / NoREC / PQS)',
    dimension: 'Mechanism',
    priority: 'P2',
    status: 'CANDIDATE',
    description: 'Validate relational partitioning invariants (Q(P) UNION Q(NOT P) UNION Q(P IS NULL) == Q(TRUE)).',
    applicableDbms: 'ALL',
    applicableContexts: ['where_clause', 'numeric', 'single_quote_string'],
    applicableTransports: 'ALL',
    researchSource: 'Rigger & Su (USENIX Security 2020)',
  },
  M10: {
    id: 'M10',
    name: 'JSON / XML Structured Document SQL Operator Injection',
    dimension: 'Mechanism',
    priority: 'P1',
    status: 'CONFIRMED',
    description: 'Exploit JSON/XML query extraction operators (e.g. ->>, JSON_VALUE, OPENXML, xpath) in modern REST APIs.',
    applicableDbms: ['PostgreSQL', 'MySQL', 'Microsoft SQL Server', 'Oracle', 'SQLite'],
    applicableContexts: ['json_derived', 'xml_derived', 'where_clause'],
    applicableTransports: ['body_json', 'body_xml'],
    researchSource: 'PostgreSQL JSON Path Operators; RFC 8259',
  },
  M11: {
    id: 'M11',
    name: 'Dynamic Query / Stored Procedure & Exec Parameter Injection',
    dimension: 'Mechanism',
    priority: 'P1',
    status: 'CONFIRMED',
    description: 'Escape nested dynamic SQL within stored procedures, EXEC(), EXECUTE IMMEDIATE, and sp_executesql contexts.',
    applicableDbms: ['Microsoft SQL Server', 'Oracle', 'PostgreSQL', 'MySQL'],
    applicableContexts: ['subquery', 'where_clause', 'numeric', 'single_quote_string'],
    applicableTransports: 'ALL',
    researchSource: 'CWE-89; Microsoft T-SQL Dynamic Execution Guide',
  },
  M12: {
    id: 'M12',
    name: 'Charset / Multi-byte & Encoding Mismatch Injection',
    dimension: 'Mechanism',
    priority: 'P1',
    status: 'CONFIRMED',
    description: 'Bypass sanitization via multi-byte character eating (GBK %df\', Big5), UTF-8 overlong sequences, and collation differences.',
    applicableDbms: ['MySQL', 'PostgreSQL', 'SQLite'],
    applicableContexts: ['single_quote_string', 'double_quote_string'],
    applicableTransports: 'ALL',
    researchSource: 'Chris Shiflett GBK Vulnerability; Unicode Security Standard',
  },
  M13: {
    id: 'M13',
    name: 'Database File System & Operating System Bridge Injection',
    dimension: 'Mechanism',
    priority: 'P2',
    status: 'CONFIRMED',
    description: 'Execute authorized read/write operations on database server host file systems (e.g. pg_read_file, xp_cmdshell, LOAD_FILE).',
    applicableDbms: ['PostgreSQL', 'Microsoft SQL Server', 'MySQL'],
    applicableContexts: ['numeric', 'single_quote_string'],
    applicableTransports: 'ALL',
    researchSource: 'CWE-73; Database Privilege Models',
  },
  M14: {
    id: 'M14',
    name: 'Privilege Escalation & DB Link Lateral Pivot',
    dimension: 'Mechanism',
    priority: 'P2',
    status: 'CANDIDATE',
    description: 'Traverse database links, OPENQUERY, OPENROWSET, and foreign data wrappers to access adjacent data stores.',
    applicableDbms: ['Microsoft SQL Server', 'Oracle', 'PostgreSQL'],
    applicableContexts: 'ALL',
    applicableTransports: 'ALL',
    researchSource: 'Database Linking Assessment Research',
  },
  M15: {
    id: 'M15',
    name: 'NewSQL / Distributed Consensus & Hybrid Engine Injection',
    dimension: 'Mechanism',
    priority: 'P2',
    status: 'CANDIDATE',
    description: 'Probe distributed NewSQL dialects (CockroachDB, TiDB, YugabyteDB) for parser differentials and Raft partition anomalies.',
    applicableDbms: 'ALL',
    applicableContexts: 'ALL',
    applicableTransports: 'ALL',
    researchSource: 'NewSQL Dialect Syntactic Matrices 2024-2026',
  },
  M16: {
    id: 'M16',
    name: 'Vector DB & AI Embedding Query Operator Injection',
    dimension: 'Mechanism',
    priority: 'P2',
    status: 'CANDIDATE',
    description: 'Manipulate vector similarity search operators (<->, <=>, cosine distances) in pgvector and hybrid retrieval systems.',
    applicableDbms: ['PostgreSQL', 'SQLite'],
    applicableContexts: ['where_clause', 'numeric', 'subquery'],
    applicableTransports: ['body_json', 'query'],
    researchSource: 'pgvector SQL Operators Spec 2024',
  },
  M17: {
    id: 'M17',
    name: 'Cloud Data Warehouse & Columnar MPP Analytical Injection',
    dimension: 'Mechanism',
    priority: 'P1',
    status: 'CONFIRMED',
    description: 'Exploit cloud analytical engines (Snowflake, BigQuery, ClickHouse) via specialized timing functions, dataset isolation boundaries, and array unnest expressions.',
    applicableDbms: ['Snowflake', 'Google BigQuery', 'ClickHouse'],
    applicableContexts: ['where_clause', 'numeric', 'single_quote_string', 'order_by_clause'],
    applicableTransports: ['query', 'body_json'],
    researchSource: 'Cloud DW Security Research; BigQuery SQL Syntax Spec',
  },
  M18: {
    id: 'M18',
    name: 'Object-Relational Mapping (ORM) & Query Compiler AST Injection',
    dimension: 'Mechanism',
    priority: 'P1',
    status: 'CONFIRMED',
    description: 'Bypass parameterized boundaries via ORM abstraction flaws, HQL/JPQL property path traversal, Prisma raw queries, and GraphQL AST join construction.',
    applicableDbms: 'ALL',
    applicableContexts: ['where_clause', 'subquery', 'order_by_clause', 'identifier'],
    applicableTransports: ['query', 'body_json', 'graphql'],
    researchSource: 'OWASP ORM Injection Prevention Cheat Sheet; CWE-89',
  },
};

export const MASTER_ATTACK_TAXONOMY: Record<string, TaxonomyDimensionNode> = {
  A01: {
    id: 'A01',
    name: 'Value / WHERE Clause Injection',
    dimension: 'Syntactic Context',
    priority: 'P0',
    status: 'CONFIRMED',
    description: 'String literal boundary breakouts (\', ", \\) within filtering predicates to evaluate arbitrary boolean logic or subqueries.',
    applicableDbms: 'ALL',
    applicableContexts: ['where_clause', 'single_quote_string', 'double_quote_string', 'parenthesized_string'],
    applicableTransports: 'ALL',
    researchSource: 'OWASP WSTG-INPV-05; CWE-89',
  },
  A02: {
    id: 'A02',
    name: 'Numeric-Context Injection',
    dimension: 'Syntactic Context',
    priority: 'P0',
    status: 'CONFIRMED',
    description: 'Injection into unquoted numeric literal slots, exploiting absence of quote boundaries and arithmetic operators (e.g. 100-0+...).',
    applicableDbms: 'ALL',
    applicableContexts: ['numeric', 'where_clause'],
    applicableTransports: 'ALL',
    researchSource: 'CWE-89; PortSwigger SQLi Lab 01',
  },
  A03: {
    id: 'A03',
    name: 'LIKE / Pattern Context Injection',
    dimension: 'Syntactic Context',
    priority: 'P0',
    status: 'CONFIRMED',
    description: 'Exploiting wildcard character expansion (%, _, [a-z]) and custom ESCAPE clauses within LIKE/ILIKE and regex operators.',
    applicableDbms: 'ALL',
    applicableContexts: ['like_clause', 'where_clause'],
    applicableTransports: 'ALL',
    researchSource: 'CWE-89; OWASP Wildcard Injection Cheat Sheet',
  },
  A04: {
    id: 'A04',
    name: 'ORDER BY Expression Injection',
    dimension: 'Syntactic Context',
    priority: 'P0',
    status: 'CONFIRMED',
    description: 'Injecting into sorting position indicators or CASE WHEN statements where parameterized binding is unsupported by SQL drivers.',
    applicableDbms: 'ALL',
    applicableContexts: ['order_by_clause'],
    applicableTransports: ['query', 'body_form', 'body_json'],
    researchSource: 'PortSwigger SQLi in ORDER BY; USENIX Security 2020',
  },
  A05: {
    id: 'A05',
    name: 'GROUP BY / HAVING Expression Injection',
    dimension: 'Syntactic Context',
    priority: 'P1',
    status: 'CONFIRMED',
    description: 'Manipulating post-aggregation grouping clauses and conditional HAVING expressions evaluated after aggregate functions.',
    applicableDbms: 'ALL',
    applicableContexts: ['group_by_clause', 'having_clause'],
    applicableTransports: 'ALL',
    researchSource: 'CWE-89; Database SQL Aggregate Specifications',
  },
  A06: {
    id: 'A06',
    name: 'LIMIT / OFFSET Clause Injection',
    dimension: 'Syntactic Context',
    priority: 'P1',
    status: 'CONFIRMED',
    description: 'Pagination parameter breakouts, PROCEDURE ANALYSE() execution in MySQL 5.x, or stacked statement execution in pagination limits.',
    applicableDbms: ['MySQL', 'PostgreSQL', 'SQLite'],
    applicableContexts: ['numeric'],
    applicableTransports: ['query', 'body_form', 'body_json'],
    researchSource: 'sqlmap MySQL LIMIT injection heuristics',
  },
  A07: {
    id: 'A07',
    name: 'JOIN / ON Clause Injection',
    dimension: 'Syntactic Context',
    priority: 'P1',
    status: 'CONFIRMED',
    description: 'Injecting relational table join invariants, CROSS JOIN cartesian explosions, and subquery predicates in ON conditions.',
    applicableDbms: 'ALL',
    applicableContexts: ['where_clause', 'identifier'],
    applicableTransports: 'ALL',
    researchSource: 'USENIX Security 2020 (PQS/TLP)',
  },
  A08: {
    id: 'A08',
    name: 'SELECT-List Expression Injection',
    dimension: 'Syntactic Context',
    priority: 'P1',
    status: 'CONFIRMED',
    description: 'Injecting inline expressions, subqueries, and scalar functions directly into the projected column list of a query.',
    applicableDbms: 'ALL',
    applicableContexts: ['identifier', 'subquery'],
    applicableTransports: 'ALL',
    researchSource: 'CWE-89; Query Construction Research',
  },
  A09: {
    id: 'A09',
    name: 'INSERT / UPDATE / DELETE Context Injection',
    dimension: 'Syntactic Context',
    priority: 'P0',
    status: 'CONFIRMED',
    description: 'Manipulating state-changing DML statements, column-value alignment in VALUES lists, and unconstrained WHERE boundaries in DELETE/UPDATE.',
    applicableDbms: 'ALL',
    applicableContexts: ['insert_values', 'update_set', 'where_clause'],
    applicableTransports: 'ALL',
    researchSource: 'CWE-89; OWASP WSTG-INPV-05',
  },
  A10: {
    id: 'A10',
    name: 'Dynamic Identifier Injection (Table/Column/Schema)',
    dimension: 'Structural Context',
    priority: 'P0',
    status: 'CONFIRMED',
    description: 'Injecting dynamic schema, table, column names, aliases, or sort directions where parameterization is structurally impossible.',
    applicableDbms: 'ALL',
    applicableContexts: ['identifier', 'order_by_clause'],
    applicableTransports: ['query', 'body_form', 'body_json'],
    researchSource: 'CWE-89; PortSwigger Identifier Escaping Guide',
  },
  A11: {
    id: 'A11',
    name: 'Dynamic Function & Operator Injection',
    dimension: 'Structural Context',
    priority: 'P1',
    status: 'CONFIRMED',
    description: 'Dynamically selecting database aggregate, scalar, or user-defined functions and arithmetic/comparison operators.',
    applicableDbms: 'ALL',
    applicableContexts: ['identifier', 'where_clause'],
    applicableTransports: 'ALL',
    researchSource: 'Dynamic SQL Sanitization Research',
  },
  A12: {
    id: 'A12',
    name: 'CTE / WITH & Recursive Query Injection',
    dimension: 'Query Construction',
    priority: 'P1',
    status: 'CONFIRMED',
    description: 'Injecting into Common Table Expressions (CTE) or recursive anchor/recursive members to execute arbitrary hierarchical subqueries.',
    applicableDbms: ['PostgreSQL', 'Microsoft SQL Server', 'Oracle', 'SQLite', 'MySQL'],
    applicableContexts: ['subquery', 'where_clause'],
    applicableTransports: 'ALL',
    researchSource: 'SQL-99 CTE Security Specifications',
  },
  A13: {
    id: 'A13',
    name: 'Window-Function Expression Injection',
    dimension: 'Query Construction',
    priority: 'P2',
    status: 'CONFIRMED',
    description: 'Injecting OVER(PARTITION BY ... ORDER BY ...) window framing and analytic function clauses to alter aggregation boundaries.',
    applicableDbms: ['PostgreSQL', 'Microsoft SQL Server', 'Oracle', 'MySQL', 'ClickHouse'],
    applicableContexts: ['order_by_clause', 'subquery'],
    applicableTransports: 'ALL',
    researchSource: 'Modern Analytic SQL Research',
  },
  A14: {
    id: 'A14',
    name: 'Subquery & EXISTS Clause Manipulation',
    dimension: 'Query Construction',
    priority: 'P0',
    status: 'CONFIRMED',
    description: 'Constructing correlated subqueries, NOT EXISTS filters, and scalar subquery comparisons for side-channel data extraction.',
    applicableDbms: 'ALL',
    applicableContexts: ['subquery', 'where_clause', 'having_clause'],
    applicableTransports: 'ALL',
    researchSource: 'OWASP Blind SQLi Testing Guide',
  },
  A15: {
    id: 'A15',
    name: 'Set-Operation Injection (UNION, INTERSECT, EXCEPT)',
    dimension: 'Query Construction',
    priority: 'P0',
    status: 'CONFIRMED',
    description: 'Appending secondary result sets via UNION, INTERSECT, or EXCEPT/MINUS with automated NULL-padding and type harmonization.',
    applicableDbms: 'ALL',
    applicableContexts: ['numeric', 'single_quote_string', 'where_clause'],
    applicableTransports: 'ALL',
    researchSource: 'CWE-89; PortSwigger UNION Attacks',
  },
  A16: {
    id: 'A16',
    name: 'Stored-Program & Procedure Parameter Injection',
    dimension: 'Execution Runtime',
    priority: 'P0',
    status: 'CONFIRMED',
    description: 'Escaping nested quotation boundaries inside dynamic SQL wrappers (sp_executesql, EXECUTE IMMEDIATE, EXEC()).',
    applicableDbms: ['Microsoft SQL Server', 'Oracle', 'PostgreSQL', 'MySQL'],
    applicableContexts: ['subquery', 'where_clause'],
    applicableTransports: 'ALL',
    researchSource: 'Microsoft T-SQL & Oracle PL/SQL Dynamic Security Best Practices',
  },
  A17: {
    id: 'A17',
    name: 'Database Trigger & Scheduled Event Injection',
    dimension: 'Execution Runtime',
    priority: 'P2',
    status: 'CANDIDATE',
    description: 'Injecting payloads that activate asynchronously during database trigger firings or scheduled cron/event execution jobs.',
    applicableDbms: ['MySQL', 'PostgreSQL', 'Microsoft SQL Server', 'Oracle'],
    applicableContexts: ['insert_values', 'update_set'],
    applicableTransports: 'ALL',
    researchSource: 'Database Event & Trigger Hardening Guidelines',
  },
  A18: {
    id: 'A18',
    name: 'Second-Order & Asynchronous Storage Injection',
    dimension: 'Execution Runtime',
    priority: 'P0',
    status: 'CONFIRMED',
    description: 'Storing dormant payloads into persistent storage that execute when queried by administrative panels, reports, or sync workers.',
    applicableDbms: 'ALL',
    applicableContexts: 'ALL',
    applicableTransports: 'ALL',
    researchSource: 'PortSwigger Second-Order SQLi (00100210)',
  },
  A19: {
    id: 'A19',
    name: 'ORM & Query-Builder AST Boundary Flaws',
    dimension: 'Framework & Abstraction',
    priority: 'P0',
    status: 'CONFIRMED',
    description: 'Exploiting flaws in ORM query builders (Hibernate, Prisma, TypeORM, Django, Sequelize) via raw escape hatches and path traversal.',
    applicableDbms: 'ALL',
    applicableContexts: ['where_clause', 'subquery', 'order_by_clause', 'identifier'],
    applicableTransports: ['query', 'body_json'],
    researchSource: 'CVE-2020-7471; OWASP ORM Injection Cheat Sheet',
  },
  A20: {
    id: 'A20',
    name: 'GraphQL-to-SQL Compiler Injection',
    dimension: 'Framework & Abstraction',
    priority: 'P1',
    status: 'CONFIRMED',
    description: 'Manipulating GraphQL queries, directives, and filter arguments that transpile into vulnerable raw SQL fragments (Hasura, PostGraphile).',
    applicableDbms: ['PostgreSQL', 'MySQL', 'Microsoft SQL Server'],
    applicableContexts: ['where_clause', 'subquery'],
    applicableTransports: ['graphql', 'body_json'],
    researchSource: 'GraphQL Security Testing Standards 2024-2026',
  },
  A21: {
    id: 'A21',
    name: 'JSON / XML Document Operator Injection',
    dimension: 'Framework & Abstraction',
    priority: 'P1',
    status: 'CONFIRMED',
    description: 'Injecting malicious paths or operators into JSON/XML extraction functions (->>, JSON_VALUE, OPENXML, xpath, json_extract).',
    applicableDbms: ['PostgreSQL', 'MySQL', 'Microsoft SQL Server', 'Oracle', 'SQLite'],
    applicableContexts: ['json_derived', 'xml_derived', 'where_clause'],
    applicableTransports: ['body_json', 'body_xml'],
    researchSource: 'RFC 8259; PostgreSQL JSON Path Syntax',
  },
  A22: {
    id: 'A22',
    name: 'Encoding, Canonicalization & Normalization Smuggling',
    dimension: 'Transport & Evasion',
    priority: 'P0',
    status: 'CONFIRMED',
    description: 'Evading perimeter WAF inspection via multi-stage URL decoding, Unicode NFC/NFKD normalization, and UTF-16/32 character conversion.',
    applicableDbms: 'ALL',
    applicableContexts: 'ALL',
    applicableTransports: 'ALL',
    researchSource: 'Unicode Security Consortium TR36/TR39; WAF Evasion Research',
  },
  A23: {
    id: 'A23',
    name: 'Charset, Multi-byte & Collation Collisions',
    dimension: 'Transport & Evasion',
    priority: 'P1',
    status: 'CONFIRMED',
    description: 'Exploiting multibyte escape consumption (GBK %df\', Big5), overlong UTF-8, and collation equivalences (German sharp-s ß = ss).',
    applicableDbms: ['MySQL', 'PostgreSQL', 'SQLite'],
    applicableContexts: ['single_quote_string', 'double_quote_string'],
    applicableTransports: 'ALL',
    researchSource: 'Chris Shiflett GBK Vulnerability; Unicode Collation Specs',
  },
  A24: {
    id: 'A24',
    name: 'Authentication & Authorization Query Manipulation',
    dimension: 'Application Logic',
    priority: 'P0',
    status: 'CONFIRMED',
    description: 'Tautology and comment injection inside login credentials verification, role assignment queries, and password reset workflows.',
    applicableDbms: 'ALL',
    applicableContexts: ['single_quote_string', 'where_clause'],
    applicableTransports: ['body_form', 'body_json', 'header'],
    researchSource: 'OWASP WSTG-ATHN-01; CWE-287',
  },
  A25: {
    id: 'A25',
    name: 'Multi-Tenant Predicate & RLS Boundary Tampering',
    dimension: 'Application Logic',
    priority: 'P0',
    status: 'CONFIRMED',
    description: 'Overriding tenant_id isolation predicates and Row-Level Security (RLS) filter policies to leak or manipulate cross-tenant data.',
    applicableDbms: 'ALL',
    applicableContexts: ['where_clause', 'numeric', 'single_quote_string'],
    applicableTransports: 'ALL',
    researchSource: 'Multi-Tenant Cloud Security Architecture Guide',
  },
  A26: {
    id: 'A26',
    name: 'Transaction, Isolation & Concurrency SQLi',
    dimension: 'Execution Runtime',
    priority: 'P2',
    status: 'CANDIDATE',
    description: 'Manipulating transaction isolation boundaries (READ UNCOMMITTED), connection pool session states, and concurrency race conditions.',
    applicableDbms: 'ALL',
    applicableContexts: ['where_clause', 'subquery'],
    applicableTransports: 'ALL',
    researchSource: 'ACID Transaction Security Models; PortSwigger Race Conditions',
  },
  A27: {
    id: 'A27',
    name: 'Multi-Channel Blind Inference (Content/DOM/Status)',
    dimension: 'Detection Oracle',
    priority: 'P0',
    status: 'CONFIRMED',
    description: 'High-speed bitwise differential inference using binary bisection across HTTP status codes, DOM diffs, headers, and content hashes.',
    applicableDbms: 'ALL',
    applicableContexts: 'ALL',
    applicableTransports: 'ALL',
    researchSource: 'Halfond & Orso (2006); PortSwigger Blind SQLi',
  },
  A28: {
    id: 'A28',
    name: 'Error-Based Type Coercion & Subquery Leaks',
    dimension: 'Detection Oracle',
    priority: 'P0',
    status: 'CONFIRMED',
    description: 'Extracting arbitrary query results through explicit type casting failures (CAST/CONVERT) and mathematical overflow errors.',
    applicableDbms: ['PostgreSQL', 'Microsoft SQL Server', 'MySQL', 'Oracle'],
    applicableContexts: ['numeric', 'single_quote_string', 'where_clause'],
    applicableTransports: 'ALL',
    researchSource: 'CWE-209; PortSwigger Error SQLi',
  },
  A29: {
    id: 'A29',
    name: 'Time-Based Sequential Latency Probing (SPRT)',
    dimension: 'Detection Oracle',
    priority: 'P0',
    status: 'CONFIRMED',
    description: 'Robust statistical latency evaluation using Wald Sequential Probability Ratio Test (SPRT) to eliminate false positives under network jitter.',
    applicableDbms: 'ALL',
    applicableContexts: 'ALL',
    applicableTransports: 'ALL',
    researchSource: 'Wald (1945) SPRT; Sentinel Causal Latency Engine',
  },
  A30: {
    id: 'A30',
    name: 'Out-of-Band (OAST) Network Interaction',
    dimension: 'Detection Oracle',
    priority: 'P0',
    status: 'CONFIRMED',
    description: 'Coercing external DNS, HTTP, and SMB NetNTLM network connections from database servers behind restrictive firewalls.',
    applicableDbms: ['Oracle', 'Microsoft SQL Server', 'MySQL', 'PostgreSQL'],
    applicableContexts: 'ALL',
    applicableTransports: 'ALL',
    researchSource: 'Burp Collaborator / OAST Standard; CWE-89',
  },
  A31: {
    id: 'A31',
    name: 'Metamorphic Invariant Testing (TLP / NoREC / PQS)',
    dimension: 'Verification Oracle',
    priority: 'P1',
    status: 'CONFIRMED',
    description: 'USENIX Security 2020 metamorphic invariants: verifying relational partitioning equivalences (TLP, NoREC, PQS) to find logic bugs.',
    applicableDbms: 'ALL',
    applicableContexts: ['where_clause', 'numeric', 'single_quote_string'],
    applicableTransports: 'ALL',
    researchSource: 'Rigger & Su (USENIX Security 2020)',
  },
  A32: {
    id: 'A32',
    name: 'Cloud DBaaS & Federated Lakehouse Injection',
    dimension: 'Ecosystem & Architecture',
    priority: 'P1',
    status: 'CONFIRMED',
    description: 'Auditing cloud metadata exfiltration (pg_net, UTL_HTTP), external object-storage stages (S3, Azure Blob), and federated data connectors.',
    applicableDbms: ['PostgreSQL', 'Snowflake', 'Oracle', 'Generic SQL'],
    applicableContexts: ['where_clause', 'subquery'],
    applicableTransports: 'ALL',
    researchSource: 'Cloud DBaaS Security Whitepapers 2024-2026',
  },
  A33: {
    id: 'A33',
    name: 'Distributed NewSQL & Consensus Parser Injection',
    dimension: 'Ecosystem & Architecture',
    priority: 'P2',
    status: 'CONFIRMED',
    description: 'Exploiting parser differentials and Raft distributed transaction anomalies across CockroachDB, TiDB, and YugabyteDB.',
    applicableDbms: ['CockroachDB', 'Generic SQL'],
    applicableContexts: 'ALL',
    applicableTransports: 'ALL',
    researchSource: 'Distributed Database Security Matrices 2025',
  },
  A34: {
    id: 'A34',
    name: 'Analytical & Columnar Warehouse MPP Injection',
    dimension: 'Ecosystem & Architecture',
    priority: 'P1',
    status: 'CONFIRMED',
    description: 'Exploiting cloud data warehouses (Snowflake, BigQuery, ClickHouse) using array unnest Cartesian delay, SYSTEM$WAIT, and vectorized functions.',
    applicableDbms: ['Snowflake', 'Google BigQuery', 'ClickHouse'],
    applicableContexts: ['where_clause', 'numeric', 'single_quote_string', 'order_by_clause'],
    applicableTransports: ['query', 'body_json'],
    researchSource: 'Cloud DW Security Research; BigQuery SQL Syntax Spec',
  },
  A35: {
    id: 'A35',
    name: 'Vector DB & AI Embedding Similarity Operator Injection',
    dimension: 'Modern AI / Emerging',
    priority: 'P2',
    status: 'CONFIRMED',
    description: 'Manipulating vector similarity distance operators (<->, <=>, cosine distances) in pgvector and hybrid RAG semantic search pipelines.',
    applicableDbms: ['PostgreSQL', 'SQLite'],
    applicableContexts: ['where_clause', 'numeric', 'subquery'],
    applicableTransports: ['body_json', 'query'],
    researchSource: 'pgvector SQL Operators Spec 2024-2026',
  },
  A36: {
    id: 'A36',
    name: 'DBMS-Specific Extension & Dialect Boundary Injection',
    dimension: 'Engine Dialects',
    priority: 'P0',
    status: 'CONFIRMED',
    description: 'Leveraging unique dialect features: H2 Java aliases, SQLite ATTACH DATABASE, PostgreSQL lo_export, MySQL @@plugin_dir, MSSQL xp_cmdshell.',
    applicableDbms: 'ALL',
    applicableContexts: 'ALL',
    applicableTransports: 'ALL',
    researchSource: 'Comprehensive Database Engine Security Manuals',
  },
  A37: {
    id: 'A37',
    name: 'Query-Compiler & AST Translation Injection',
    dimension: 'Framework & Abstraction',
    priority: 'P1',
    status: 'CONFIRMED',
    description: 'Attacking compiler translation bugs in LINQ-to-SQL, JPA Criteria API, Slick, and JOOQ AST expression trees.',
    applicableDbms: 'ALL',
    applicableContexts: ['where_clause', 'order_by_clause', 'identifier'],
    applicableTransports: 'ALL',
    researchSource: 'Query Compiler AST Vulnerability Research',
  },
  A38: {
    id: 'A38',
    name: 'API Transport & Protocol Header Injection',
    dimension: 'Transport & Protocol',
    priority: 'P0',
    status: 'CONFIRMED',
    description: 'Delivering SQL injection payloads through unconventional transports: HTTP headers (X-Forwarded-For, Referer), cookies, WebSockets, and gRPC.',
    applicableDbms: 'ALL',
    applicableContexts: 'ALL',
    applicableTransports: ['header', 'cookie', 'body_json', 'body_multipart', 'graphql'],
    researchSource: 'CVE-2023-34362 (MOVEit); HTTP Header Injection Standards',
  },
  A39: {
    id: 'A39',
    name: 'Automated Schema & Metadata Discovery',
    dimension: 'Reconnaissance & Extraction',
    priority: 'P0',
    status: 'CONFIRMED',
    description: 'Systematic querying of system catalog tables, information_schema, sys.*, and SQLite sqlite_master to reconstruct the complete database schema.',
    applicableDbms: 'ALL',
    applicableContexts: ['where_clause', 'numeric', 'single_quote_string'],
    applicableTransports: 'ALL',
    researchSource: 'SQL-92 Information Schema Standards; sqlmap core engine',
  },
  A40: {
    id: 'A40',
    name: 'Application-State & Asynchronous Lifecycle Flows',
    dimension: 'Application Logic',
    priority: 'P1',
    status: 'CONFIRMED',
    description: 'Auditing multi-step state machine transitions, event sourcing stores, and asynchronous worker queue ingestion for deferred SQL execution.',
    applicableDbms: 'ALL',
    applicableContexts: 'ALL',
    applicableTransports: 'ALL',
    researchSource: 'Distributed Systems & Event-Driven SQL Architecture',
  },
};

export const OBSERVATION_ORACLES = [
  'DIRECT_IN_BAND',
  'UNION_CANARY_REFLECTION',
  'VERBOSE_SYNTAX_ERROR',
  'CAST_TYPE_ERROR',
  'BOOLEAN_STATUS_CODE',
  'BOOLEAN_CONTENT_DIFF',
  'BOOLEAN_HEADER_REDIRECT',
  'DOM_STRUCTURAL_DIFF',
  'FIXED_TIME_DELAY',
  'SPRT_STATISTICAL_LATENCY',
  'OOB_DNS_INTERACTION',
  'OOB_HTTP_INTERACTION',
  'OOB_SMB_NTLM',
  'METAMORPHIC_INVARIANT',
  'STATE_CHANGE_SIDE_EFFECT',
] as const;

export type ObservationOracleType = typeof OBSERVATION_ORACLES[number];

export const NORMALIZED_TAXONOMY = {
  syntacticContexts: [
    { id: 'CTX_WHERE', name: 'WHERE Clause Predicate', description: 'String and literal breakouts in filtering predicates' },
    { id: 'CTX_NUMERIC', name: 'Unquoted Numeric Expression', description: 'Arithmetic operator and numeric literal slots' },
    { id: 'CTX_LIKE', name: 'LIKE / Pattern Expression', description: 'Pattern matching wildcards and ESCAPE clauses' },
    { id: 'CTX_ORDER_BY', name: 'ORDER BY Expression', description: 'Sorting column indicators and CASE statements' },
    { id: 'CTX_GROUP_BY', name: 'GROUP BY Expression', description: 'Post-aggregation grouping clauses' },
    { id: 'CTX_HAVING', name: 'HAVING Clause Predicate', description: 'Conditional aggregation filters' },
    { id: 'CTX_LIMIT_OFFSET', name: 'LIMIT / OFFSET Clause', description: 'Pagination and row count constraints' },
    { id: 'CTX_JOIN_ON', name: 'JOIN / ON Condition', description: 'Relational join predicates and cartesian products' },
    { id: 'CTX_SELECT_LIST', name: 'SELECT-List Projection', description: 'Scalar expressions in query projection' },
    { id: 'CTX_INSERT_VALUES', name: 'INSERT VALUES List', description: 'Column alignment in insertion tuples' },
    { id: 'CTX_UPDATE_SET', name: 'UPDATE SET Assignment', description: 'Assignment expressions in state modification' },
    { id: 'CTX_DELETE_WHERE', name: 'DELETE WHERE Condition', description: 'Unconstrained deletion boundaries' },
    { id: 'CTX_MERGE_CLAUSE', name: 'MERGE INTO / UPSERT Condition', description: 'ON condition and WHEN MATCHED/NOT MATCHED branches' },
    { id: 'CTX_SUBQUERY', name: 'Subquery / EXISTS Clause', description: 'Correlated and scalar nested subqueries' },
    { id: 'CTX_CTE_WITH', name: 'CTE / WITH Query', description: 'Common Table Expressions and recursive anchors' },
    { id: 'CTX_WINDOW_FN', name: 'Window Function Expression', description: 'OVER(PARTITION BY ... ORDER BY ...) framing' },
    { id: 'CTX_DATE_TIME', name: 'Date / Time Temporal Literal', description: 'Temporal equality and interval arithmetic' },
    { id: 'CTX_VECTOR_OP', name: 'Vector Similarity Operator', description: 'pgvector <-> and <=> distance operators' },
    { id: 'CTX_ARRAY_EXPR', name: 'Array / Collection Expression', description: 'Array membership ANY() and unnesting' },
    { id: 'CTX_IDENTIFIER', name: 'Dynamic Identifier', description: 'Table, column, schema names, and sort directions' },
  ],
  mechanisms: Object.values(MECHANISMS),
  targetEngines: [
    // Tier 1: Core / Tested
    { id: 'PostgreSQL', name: 'PostgreSQL', tier: 'TIER_1_TESTED' as const },
    { id: 'MySQL', name: 'MySQL', tier: 'TIER_1_TESTED' as const },
    { id: 'Microsoft SQL Server', name: 'Microsoft SQL Server', tier: 'TIER_1_TESTED' as const },
    { id: 'Oracle', name: 'Oracle', tier: 'TIER_1_TESTED' as const },
    { id: 'SQLite', name: 'SQLite', tier: 'TIER_1_TESTED' as const },
    // Tier 2: Implemented Adapters
    { id: 'Snowflake', name: 'Snowflake', tier: 'TIER_2_ADAPTER' as const },
    { id: 'Google BigQuery', name: 'Google BigQuery', tier: 'TIER_2_ADAPTER' as const },
    { id: 'ClickHouse', name: 'ClickHouse', tier: 'TIER_2_ADAPTER' as const },
    { id: 'CockroachDB', name: 'CockroachDB', tier: 'TIER_2_ADAPTER' as const },
    { id: 'MariaDB', name: 'MariaDB', tier: 'TIER_2_ADAPTER' as const },
    { id: 'IBM Db2', name: 'IBM Db2', tier: 'TIER_2_ADAPTER' as const },
    { id: 'H2', name: 'H2', tier: 'TIER_2_ADAPTER' as const },
    { id: 'Microsoft Access', name: 'Microsoft Access', tier: 'TIER_2_ADAPTER' as const },
    { id: 'Amazon Redshift', name: 'Amazon Redshift', tier: 'TIER_2_ADAPTER' as const },
    { id: 'DuckDB', name: 'DuckDB', tier: 'TIER_2_ADAPTER' as const },
    { id: 'Trino', name: 'Trino', tier: 'TIER_2_ADAPTER' as const },
    { id: 'Presto', name: 'Presto', tier: 'TIER_2_ADAPTER' as const },
    { id: 'Vertica', name: 'Vertica', tier: 'TIER_2_ADAPTER' as const },
    // Tier 3: Aliased Stubs
    { id: 'YugabyteDB', name: 'YugabyteDB', tier: 'TIER_3_ALIASED' as const },
    { id: 'TimescaleDB', name: 'TimescaleDB', tier: 'TIER_3_ALIASED' as const },
    { id: 'AlloyDB', name: 'AlloyDB', tier: 'TIER_3_ALIASED' as const },
    { id: 'Vitess', name: 'Vitess', tier: 'TIER_3_ALIASED' as const },
    { id: 'SingleStore', name: 'SingleStore', tier: 'TIER_3_ALIASED' as const },
    { id: 'Apache Doris', name: 'Apache Doris', tier: 'TIER_3_ALIASED' as const },
    { id: 'Azure Synapse', name: 'Azure Synapse', tier: 'TIER_3_ALIASED' as const },
    { id: 'Databricks SQL', name: 'Databricks SQL', tier: 'TIER_3_ALIASED' as const },
    { id: 'Teradata', name: 'Teradata', tier: 'TIER_3_ALIASED' as const },
    { id: 'Firebird', name: 'Firebird', tier: 'TIER_3_ALIASED' as const },
    { id: 'SAP HANA', name: 'SAP HANA', tier: 'TIER_3_ALIASED' as const },
    { id: 'Generic SQL', name: 'Generic SQL', tier: 'TIER_1_TESTED' as const },
  ],
  transports: [
    'query',
    'body_form',
    'body_multipart',
    'body_json',
    'body_xml',
    'header',
    'cookie',
    'path',
    'graphql',
  ],
  observationOracles: OBSERVATION_ORACLES,
  statementFamilies: [
    'SELECT',
    'INSERT',
    'UPDATE',
    'DELETE',
    'MERGE',
    'UPSERT',
    'CALL',
    'EXEC',
    'DDL',
    'TRANSACTION',
    'EXPLAIN',
    'PREPARE',
    'COPY_BULK',
  ],
};

export const TaxonomyCatalog = {
  MECHANISMS,
  MASTER_ATTACK_TAXONOMY,
  OBSERVATION_ORACLES,
  NORMALIZED_TAXONOMY,
};


