from pathlib import Path
from docx import Document
from docx.shared import Pt
from docx.oxml.ns import qn

BASE=Path(r'C:\Users\Legion 5 pro\Desktop\cyber sec')
def run_font(r,size=10,bold=False):
 r.font.name='Aptos';r._element.rPr.rFonts.set(qn('w:ascii'),'Aptos');r._element.rPr.rFonts.set(qn('w:hAnsi'),'Aptos');r.font.size=Pt(size);r.bold=bold
def add_page(d,title,paras,bullets):
 d.add_page_break();h=d.add_paragraph(style='Heading 1');h.paragraph_format.space_before=Pt(4);h.paragraph_format.space_after=Pt(6);run_font(h.add_run(title),13,True)
 for text in paras:
  p=d.add_paragraph();p.paragraph_format.space_after=Pt(6);run_font(p.add_run(text),10)
 for text in bullets:
  p=d.add_paragraph(style='List Bullet');p.paragraph_format.space_after=Pt(4);run_font(p.add_run(text),10)
def ext_lung():
 f=BASE/'Assignment_5_Lung_Cancer_Detection_ML_Style.docx';d=Document(f)
 add_page(d,'13. APPENDIX A - CNN ARCHITECTURE AND DATA FLOW',['The model receives a standardized CT image, applies normalization, learns image features through convolution and pooling layers, and produces a class probability through a sigmoid output layer. This appendix records the design used for the academic demonstration.'],['Input: 128 x 128 RGB CT image after resizing.','Feature extraction: convolution layers learn edges, textures and shape patterns.','Pooling: reduces spatial dimensions and computational load.','Dropout: reduces overfitting during training.','Output: probability score used only for the illustrative normal / cancer-suspicious class.'])
 add_page(d,'14. APPENDIX B - MODEL EVALUATION AND LIMITATIONS',['Evaluation should use a hold-out test set that was not used for training or tuning. Accuracy alone is not enough for medical-image tasks: sensitivity, specificity, precision, recall and false-negative behavior must be considered.'],['Use patient-level train/test separation to avoid data leakage.','Assess performance across scanners, hospitals, ages and clinical populations.','Review false positives and false negatives with qualified clinicians.','Do not use this classroom model for diagnosis, triage or treatment decisions.','Document data provenance, consent, bias risks and validation results.'])
 d.save(f)
def ext_malware():
 f=BASE/'Malware_Infection_Incident_Response_Report.docx';d=Document(f)
 pages=[
 ('Appendix A - Incident Command Structure',['A coordinated incident requires clear accountability and a single source of truth. The incident commander prioritizes safety, business impact and evidence preservation while technical teams execute assigned work.'],['Incident commander: approves priorities and escalation.','Forensics lead: preserves and analyzes evidence.','Endpoint lead: isolates, rebuilds and validates hosts.','Identity lead: resets accounts, tokens and privileged access.','Communications lead: provides approved internal and external updates.']),
 ('Appendix B - Evidence Preservation Checklist',['Evidence should be collected lawfully, logged with timestamps and stored in protected locations. Collection must not unnecessarily alter the affected endpoint or overwrite volatile data.'],['Record hostname, user, IP address and detection time.','Capture EDR alert details and process trees.','Preserve volatile data from representative systems when feasible.','Collect relevant Windows, DNS, proxy, firewall and identity logs.','Hash collected files and maintain chain-of-custody notes.']),
 ('Appendix C - Host Status Ledger',['The security team should track every potentially affected computer from initial alert to approved return to service. The ledger prevents duplicate work and supports management reporting.'],['Asset identifier and user.','Detection source and time.','Isolation state and evidence status.','IOC matches and suspected infection vector.','Rebuild, validation and return-to-service approval.']),
 ('Appendix D - Enterprise Hunting Plan',['Hunting looks beyond the initial 20 devices for related attacker activity. Searches should be repeated after new indicators are discovered and should include endpoints, identity systems, network telemetry and cloud logs.'],['Search known hashes, paths, domains and IP addresses.','Search for parent/child process patterns and persistence techniques.','Review anomalous authentication and privilege changes.','Identify lateral movement through remote-management protocols.','Document negative as well as positive search results.']),
 ('Appendix E - Credential Recovery Plan',['Credential recovery is required when malware may have captured passwords, tokens, browser cookies or privileged sessions. Recovery must be sequenced so that attackers cannot immediately reuse access.'],['Disable or reset high-risk accounts first.','Revoke active cloud sessions and refresh tokens.','Rotate privileged, service and API credentials.','Verify MFA enrollment and remove unauthorized methods.','Monitor for unusual sign-ins after reset.']),
 ('Appendix F - Backup and Restore Validation',['Backups support recovery only when their integrity and separation from compromised systems are verified. Restore testing should happen in an isolated environment before production cutover.'],['Identify last known good recovery points.','Verify backup access is separated from normal administrator accounts.','Scan restored files before reuse.','Test application function and data integrity.','Record restoration source, time and approver.']),
 ('Appendix G - Recovery Communications',['Recovery communication keeps leadership and users informed without exposing sensitive technical detail. Messages should state what is known, what actions users must take, and when the next update will arrive.'],['Use approved channels and a consistent cadence.','Avoid speculative attribution or breach claims.','Tell users how to report new symptoms.','Coordinate customer, regulator and insurer notices through legal counsel.','Record all material decisions and statements.']),
 ('Appendix H - Post-Incident Metrics',['Metrics help determine whether the response reduced impact and identify improvements for future incidents. Results should be reviewed by technical teams and leadership after stabilization.'],['Time to detect and time to contain.','Number of endpoints affected and rebuilt.','Time to restore essential services.','Percentage of hosts with current EDR and patches.','Completion of corrective actions and tabletop exercises.'])]
 for x in pages:add_page(d,*x)
 d.save(f)
def ext_student():
 f=BASE/'Student_Performance_Analysis_Mini_Project.docx';d=Document(f)
 pages=[
 ('Appendix B - Data Dictionary',['This appendix defines the illustrative variables used in the analysis. All records are anonymized and synthetic; the data dictionary is included to support reproducibility and responsible interpretation.'],['Study hours: self-reported weekly academic study time.','Attendance: percentage of scheduled sessions attended.','Previous score: prior examination percentage.','Sleep hours: typical nightly sleep duration.','Final score: examination score used as the outcome variable.']),
 ('Appendix C - Data Quality Checks',['Before analysis, data should be reviewed for missing values, duplicate records, impossible ranges and inconsistent units. Quality checks protect against misleading charts and incorrect statistical conclusions.'],['Check study hours and sleep hours for plausible ranges.','Verify attendance is between 0 and 100 percent.','Remove duplicate record identifiers.','Document any missing-value treatment.','Keep a reproducible record of transformations.']),
 ('Appendix D - Suggested Python Workflow',['A reproducible workflow separates loading, cleaning, exploratory analysis, statistical testing and reporting. Code should be version controlled and results regenerated when data changes.'],['Load a de-identified CSV file with Pandas.','Use describe() and missing-value checks.','Create correlation tables and figures.','Fit regression with documented assumptions.','Export only aggregated, privacy-safe results.']),
 ('Appendix E - Regression Assumptions',['Regression is useful only when its assumptions and limitations are considered. Diagnostics should be included before decisions are made from the model.'],['Inspect residual patterns for non-linearity.','Check for influential observations.','Assess multicollinearity in multiple models.','Report uncertainty, not only point estimates.','Avoid causal language for observational data.']),
 ('Appendix F - Responsible Use Guidelines',['Student analytics should support learning and equity. It must not be used as an automated system for grading, exclusion, discipline or labeling students.'],['Use the findings to offer tutoring and resources.','Provide transparency about data use.','Limit access to authorized staff.','Review potential bias and unequal access to support.','Keep teacher and student context central to decisions.'])]
 for x in pages:add_page(d,*x)
 d.save(f)
if __name__=='__main__':ext_lung();ext_malware();ext_student()
